# -*- coding: utf-8 -*-
"""edtech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FX5-n1zFnCHmKyT2aSPYEO076v4b4Yrl
"""

import pandas as pd
import numpy as np

courses = pd.read_csv('/content/courses.csv')
deliveries = pd.read_csv('/content/deliveries.csv')
students = pd.read_csv('/content/students (1).csv')
nov = pd.read_csv('/content/reg-month1.csv')
dec = pd.read_csv('/content/reg-month2.csv')
matches = pd.read_csv('/content/matches.csv')

dec

nov

students

courses

matches

pd.concat([nov,dec] , ignore_index = True)

pd.concat([nov,dec],axis = 1 )

regs = pd.concat([nov , dec ] , ignore_index = 'True')
regs

# total revenue earned
regs.merge(courses , how = 'inner' , on = 'course_id')['price'].sum()

# month by month revenue
temp_df = pd.concat([nov , dec ] , keys = ['nov' , 'dec' ]).reset_index()
temp_df.merge (courses , on='course_id').groupby('level_0')['price'].sum()

courses

# registration_table
regs.merge(students , on = 'student_id').merge(courses , on = 'course_id')[['name' ,  'course_name' , 'price']]

# pie chart for revenue/ couses
regs.merge(courses , on = 'course_id').groupby('course_name')['price'].sum().plot(kind = 'pie')

# bar chart for revenue/ couses
regs.merge(courses , on = 'course_id').groupby('course_name')['price'].sum().plot(kind = 'bar')

# student who enrolled in both the months
common_student_id = np.intersect1d(nov['student_id'] ,dec['student_id'])
common_student_id

students[students['student_id'].isin(common_student_id)]

# course with no enrollment
courses_id_list = np.setdiff1d(courses ['course_id'],regs['course_id'])
courses[courses['course_id'].isin(courses_id_list)]

# students who did not enrolled into any course
students_id_list = np.setdiff1d(students ['student_id'],regs['student_id'])
students[students['student_id'].isin(students_id_list)]

# table student name and partner
students.merge(students , how = 'inner' , left_on = 'partner' , right_on = 'student_id')[['name_x' , 'name_y']]